name: Fetch Prices & Build NAV (Sheets by Tab Name)

on:
  schedule:
    - cron: "15 21 * * *"   # daily ~05:15 SGT
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure paths
        run: |
          mkdir -p data/quotes scripts/ci

      - name: Check stocks.json exists & valid JSON
        run: |
          if [ ! -f data/stocks.json ]; then
            echo "::error::Missing data/stocks.json"
            exit 1
          fi
          sudo apt-get update && sudo apt-get install -y jq
          if ! jq . data/stocks.json > /dev/null 2>&1; then
            echo "::error::data/stocks.json is not valid JSON"
            exit 1
          fi
          echo "stocks.json snippet:"
          head -n 60 data/stocks.json

      - name: Extract tab names we will fetch (for probe)
        id: tabs
        run: |
          # Build a CSV list of tab names from symbols (COALINDIA.NS -> COALINDIA_NS)
          TABS=$(jq -r '.[].symbol' data/stocks.json | awk '{gsub(/\./,"_"); print toupper($0)}' | paste -sd "," -)
          echo "tabs=$TABS,USDINR" >> $GITHUB_OUTPUT

      - name: Probe published CSV endpoints (optional but helpful)
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          TABS: ${{ steps.tabs.outputs.tabs }}
        run: |
          IFS=',' read -ra TABLIST <<< "$TABS"
          for TAB in "${TABLIST[@]}"; do
            URL="https://docs.google.com/spreadsheets/d/${SHEET_ID}/gviz/tq?tqx=out:csv&sheet=${TAB}"
            echo "PROBE $TAB -> $URL"
            # show HTTP status and first 200 bytes
            code=$(curl -s -o /tmp/x.csv -w "%{http_code}" "$URL" || true)
            head -c 200 /tmp/x.csv || true
            echo
            echo "HTTP $code"
          done

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install pandas==2.2.2 numpy==1.26.4 requests==2.32.3

      - name: Verify fetch_prices.py exists
        run: |
          if [ ! -f scripts/ci/fetch_prices.py ]; then
            echo "::error::scripts/ci/fetch_prices.py not found (path must be scripts/ci/fetch_prices.py)"
            exit 1
          fi
          sed -n '1,200p' scripts/ci/fetch_prices.py

      - name: Run fetch_prices.py
        env:
          SHEET_ID: "1-oAHFEvGr9lhvPoMXuoedmsHOrJY2r4AgsC47tjRBCs"
          TAB_GIDS_JSON: ${{ secrets.TAB_GIDS_JSON }}
          BASE_CURRENCY: "USD"
          STARTING_CASH: "10000000"
          YEARS_BACK: "5"

          # Optional: uncomment and set if your tab names differ from the defaults
          # TAB_NAME_OVERRIDES: '{"COALINDIA.NS":"CoalIndia_NS","KIRLOSBROS.NS":"KBL_NS","USDINR":"FX"}'
        run: |
          set -euo pipefail
          python -u scripts/ci/fetch_prices.py

      - name: Show generated files
        run: |
          echo "quotes dir:"
          ls -la data/quotes || true
          echo "nav_summary.json:"
          cat data/nav_summary.json || true
          echo "nav.json head:"
          head -c 1200 data/nav.json || true
          echo

      - name: Commit changes (if any)
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add data/quotes data/nav.json data/nav_summary.json
            git commit -m "chore(data): update quotes & nav [skip ci]" || true
            git push || echo "::warning::Push failed (protected branch). Data was generated but not pushed."
          else
            echo "No changes to commit."
          fi
